# Generated by Django 2.0.7 on 2018-07-06 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_first_line', models.CharField(max_length=120)),
                ('address_second_line', models.CharField(max_length=120)),
                ('town', models.CharField(max_length=120)),
                ('city', models.CharField(max_length=120)),
                ('county', models.CharField(max_length=120)),
                ('country', models.CharField(max_length=120)),
                ('post_code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('urls', models.CharField(max_length=120)),
                ('address', models.ManyToManyField(to='project_management.Address')),
                ('clients', models.ManyToManyField(related_name='companies', to='project_management.Client')),
            ],
        ),
        migrations.CreateModel(
            name='EmailAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='email_addresses',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_management.EmailAddress'),
        ),
    ]
