# Generated by Django 2.0.7 on 2018-07-06 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0002_auto_20180706_0859'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name_plural': 'Statuses'},
        ),
        migrations.RemoveField(
            model_name='project',
            name='jobs',
        ),
        migrations.AddField(
            model_name='job',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project_management.Project'),
        ),
        migrations.AddField(
            model_name='project',
            name='status_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_management.StatusGroup'),
        ),
        migrations.AddField(
            model_name='status',
            name='status_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project_management.StatusGroup'),
            preserve_default=False,
        ),
    ]
