# Generated by Django 2.0.7 on 2018-07-06 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0003_auto_20180706_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project_management.Project'),
            preserve_default=False,
        ),
    ]
