# Generated by Django 2.0.7 on 2018-07-06 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0004_auto_20180706_1053'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=80)),
                ('hourly_rate', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='address',
            name='address_second_line',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='county',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='town',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_management.Staff'),
        ),
    ]
