# Generated by Django 2.0.7 on 2018-07-06 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0005_auto_20180706_1109'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name_plural': 'staff'},
        ),
        migrations.RenameField(
            model_name='company',
            old_name='urls',
            new_name='url',
        ),
        migrations.AddField(
            model_name='job',
            name='estimated_time',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='logged_time',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='job',
            name='deadline',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='hourly_rate',
            field=models.FloatField(default=0),
        ),
    ]
