# Generated by Django 2.0.7 on 2018-07-06 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0008_remove_address_town'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='addresses',
            field=models.ManyToManyField(related_name='addresses', to='project_management.Address'),
        ),
    ]
