# Generated by Django 2.0.7 on 2018-07-06 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0009_auto_20180706_1559'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='email_addresses',
            new_name='email_address',
        ),
    ]
